//! Ascent Datalog code generation
//!
//! This module orchestrates the generation of Ascent Datalog code for a theory.
//!
//! ## Structure
//!
//! - `relations` - Relation declarations (categories, equality, rewrites, projections)
//! - `categories` - Category exploration and term deconstruction rules
//! - `equations` - Equality/equation rules with congruence
//! - `rewrites/` - Base rewrite rules and pattern/RHS generation
//! - `congruence/` - Congruence rules for rewrites (collection, regular, binding)
//!
//! ## Generated Code Components
//!
//! 1. **Relations**: Declare all Ascent relations for terms, equality, and rewrites
//! 2. **Category Rules**: Explore term space via rewrites and deconstruct terms
//! 3. **Equation Rules**: Add reflexivity, congruence, and user-defined equalities
//! 4. **Rewrite Rules**: Base rewrites + congruence rules (propagate through constructors)

use crate::{ast::TheoryDef, utils::print_rule};
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};

mod categories;
mod equations;
mod relations;
mod writer;

pub mod congruence;
pub mod rewrites;

// Re-export key functions
pub use categories::generate_category_rules;
pub use equations::generate_equation_rules;
pub use relations::generate_relations;

// Re-export congruence types and functions used by lib.rs
pub use congruence::{extract_collection_congruence_info, generate_congruence_projections};

pub use rewrites::{generate_freshness_functions, generate_rewrite_clauses};

/// Main entry point: Generate complete Ascent source for a theory
pub fn generate_ascent_source(theory: &TheoryDef) -> TokenStream {
    let theory_name = theory.name.to_string().to_lowercase();
    let source_name = format_ident!("{}_source", theory_name);

    let relations = generate_relations(theory);
    let category_rules = generate_category_rules(theory);
    let equation_rules = generate_equation_rules(theory);
    let rewrite_rules = generate_rewrite_rules(theory);

    let result = quote! {
        ::ascent::ascent_source! {
            #source_name:

            #relations

            #category_rules

            #equation_rules

            #rewrite_rules
        }
    };
    
    // Format and write the generated Ascent source to file
    let formatted_source = format_ascent_source(&theory_name, &source_name, &relations, &category_rules, &equation_rules, &rewrite_rules);
    
    // Write to file for inspection
    if let Err(e) = writer::write_ascent_file(&theory.name.to_string(), &formatted_source) {
        eprintln!("Warning: Failed to write Ascent Datalog file: {}", e);
    }
    
    result
}

/// Format Ascent source for display and file output
fn format_ascent_source(
    theory_name: &str,
    source_name: &Ident,
    relations: &TokenStream,
    category_rules: &TokenStream,
    equation_rules: &TokenStream,
    rewrite_rules: &TokenStream,
) -> String {
    let mut output = String::new();
    
    output.push_str(&format!("// Generated Ascent Datalog for {} theory\n", theory_name));
    output.push_str("// This file is generated by the theory! macro and is for inspection only.\n");
    output.push_str("// Do not edit manually - changes will be overwritten.\n\n");
    
    output.push_str("ascent_source! {\n");
    output.push_str(&format!("    {}:\n\n", source_name));
    
    output.push_str("    // Relations\n");
    for line in relations.to_string().split(';') {
        output.push_str(&print_rule(line));
    }
    
    output.push_str("\n    // Category rules\n");
    for line in category_rules.to_string().split(';') {
        output.push_str(&print_rule(line));
    }
    
    output.push_str("\n    // Equation rules\n");
    for line in equation_rules.to_string().split(';') {
        output.push_str(&print_rule(line));
    }
    
    output.push_str("\n    // Rewrite rules\n");
    for line in rewrite_rules.to_string().split(';') {
        output.push_str(&print_rule(line));
    }
    
    output.push_str("}\n");
    
    output
}

/// Format a single Datalog rule for display
#[allow(dead_code)]
fn format_rule(line: &str) -> String {
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return String::new();
    }
    
    // Use the existing print_rule logic but return string instead of printing
    if trimmed.contains("<--") {
        // It's a rule with body
        format!("{};", trimmed)
    } else if trimmed.starts_with("relation") || trimmed.starts_with("#[") {
        // It's a relation declaration or attribute
        format!("{};", trimmed)
    } else {
        // Other content
        trimmed.to_string()
    }
}

/// Generate rewrite rules: base rewrites + congruence rules
///
/// - **Base rewrites**: Rules without premises (S => T)
/// - **Collection congruences**: If S => T, then {S, ...} => {T, ...}
/// - **Regular congruences**: If S => T, then Constructor(S) => Constructor(T)
/// - **Binding congruences**: If S => T, then (new x.S) => (new x.T)
pub fn generate_rewrite_rules(theory: &TheoryDef) -> TokenStream {
    let mut rules = Vec::new();

    // Generate base rewrite clauses (no premise)
    let base_rewrite_clauses = generate_rewrite_clauses(theory);
    rules.extend(base_rewrite_clauses);

    // Generate congruence rules (with premise: if S => T then ...)
    // For each collection congruence, generate projections and clauses
    for (cong_idx, rewrite) in theory.rewrites.iter().enumerate() {
        if let Some((source_var, target_var)) = &rewrite.premise {
            // Check if this is a collection congruence
            if let Some(cong_info) =
                extract_collection_congruence_info(&rewrite.left, source_var, target_var, theory)
            {
                // Generate all projections for this congruence
                let (projections, base_patterns) =
                    generate_congruence_projections(cong_idx, &cong_info, theory);
                rules.extend(projections);

                // Generate congruence clauses using those projections
                let congruence_clauses = congruence::generate_new_collection_congruence_clauses(
                    cong_idx,
                    &cong_info,
                    &base_patterns,
                    theory,
                );
                rules.extend(congruence_clauses);
            } else {
                // Regular (non-collection) congruence - dispatch to appropriate handler
                if let Some(rule) =
                    congruence::generate_congruence_rewrite(cong_idx, rewrite, theory)
                {
                    rules.push(rule);
                }
            }
        }
    }

    quote! {
        #(#rules)*
    }
}
