# Rust formatting configuration
# See https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Comments and documentation
wrap_comments = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true

# Formatting
fn_call_width = 80
struct_lit_width = 40
struct_variant_width = 40
array_width = 80
chain_width = 60

# Style choices
use_small_heuristics = "Default"
match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true

# Sorting
reorder_imports = true
reorder_modules = true

# Misc
edition = "2021"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true

