#![allow(
    non_local_definitions,
    clippy::crate_in_macro_def,
    clippy::empty_line_after_outer_attr
)]

use mettail_macros::theory;
use std::collections::HashMap;

// Simple integer calculator theory: supports integer literals, + and -
// Uses native i32 type for direct integer support
theory! {
    name: Calculator,
    exports {
        ![i32] as Int
    },
    terms {
        // Variables parse as VarRef nodes
        VarRef . Int ::= Var ;
        // Integer literals - handled by parser via Integer token
        // Note: NumLit is generated by parser from Integer tokens, not from this rule
        NumLit . Int ::= Var ;

        Add . Int ::= Int "+" Int ;
        Sub . Int ::= Int "-" Int ;
    },
    equations {
    },
    rewrites {
        // Variable substitution: if env_var(x, v) then VarRef(x) => NumLit(v)
        if env_var(x, v) then (VarRef x) => (NumLit v);
    }
}

//=============================================================================
// ENVIRONMENT
//=============================================================================

/// Environment for storing variable bindings
#[derive(Debug, Clone)]
pub struct CalculatorEnv {
    vars: HashMap<String, i32>,
}

impl CalculatorEnv {
    /// Create a new empty environment
    pub fn new() -> Self {
        CalculatorEnv {
            vars: HashMap::new(),
        }
    }

    /// Store a variable binding
    pub fn set(&mut self, name: String, value: i32) {
        self.vars.insert(name, value);
    }

    /// Look up a variable value
    pub fn get(&self, name: &str) -> Option<i32> {
        self.vars.get(name).copied()
    }

    /// Clear all bindings
    pub fn clear(&mut self) {
        self.vars.clear();
    }
}

impl Default for CalculatorEnv {
    fn default() -> Self {
        Self::new()
    }
}

/// Convert environment to Ascent input facts
/// Returns a vector of (variable_name, value) tuples for the env_var relation
pub fn env_to_facts(env: &CalculatorEnv) -> Vec<(String, i32)> {
    env.vars.iter().map(|(name, val)| (name.clone(), *val)).collect()
}

/// Apply rewrites to a term using environment facts
/// Returns the rewritten term (normal form) or the original if no rewrite applies
/// 
/// This implements the rewrite rule: if env_var(x, v) then (VarRef x) => (NumLit v)
/// by recursively substituting VarRef nodes with their values from the environment.
fn apply_rewrites_with_env(term: Int, env: &CalculatorEnv) -> Result<Int, String> {
    // Recursively apply variable substitution (mimicking the rewrite rule)
    substitute_vars_recursive(&term, env)
}

/// Recursively substitute VarRef nodes with NumLit values from environment
/// Implements: if env_var(x, v) then (VarRef x) => (NumLit v)
fn substitute_vars_recursive(term: &Int, env: &CalculatorEnv) -> Result<Int, String> {
    match term {
        Int::VarRef(ord_var) => {
            // Extract variable name from OrdVar
            // ord_var is already OrdVar, so we need to match the inner Var
            let var_name = match ord_var {
                mettail_runtime::OrdVar(mettail_runtime::Var::Free(ref fv)) => {
                    // pretty_name is Option<String> in moniker
                    fv.pretty_name
                        .as_ref()
                        .map(|s| s.as_str())
                        .ok_or_else(|| "Variable has no name".to_string())?
                }
                _ => return Err("Cannot substitute bound variable".to_string()),
            };
            
            // Look up value in environment (env_var(x, v))
            let val = env.get(var_name)
                .ok_or_else(|| format!("undefined variable: {}", var_name))?;
            
            // Apply rewrite: VarRef(x) => NumLit(v)
            Ok(Int::NumLit(val))
        }
        Int::NumLit(n) => Ok(Int::NumLit(*n)),
        Int::Add(a, b) => {
            let a_sub = substitute_vars_recursive(a, env)?;
            let b_sub = substitute_vars_recursive(b, env)?;
            Ok(Int::Add(Box::new(a_sub), Box::new(b_sub)))
        }
        Int::Sub(a, b) => {
            let a_sub = substitute_vars_recursive(a, env)?;
            let b_sub = substitute_vars_recursive(b, env)?;
            Ok(Int::Sub(Box::new(a_sub), Box::new(b_sub)))
        }
    }
}

//=============================================================================
// EVALUATION
//=============================================================================

impl Int {
    /// Evaluate the expression as `i32`.
    /// With native types, `NumLit` contains the integer value directly,
    /// so evaluation is straightforward.
    /// Variables (VarRef) should be substituted via rewrites before evaluation.
    pub fn eval(&self) -> i32 {
        match self {
            Int::VarRef(_) => {
                panic!("Cannot evaluate VarRef - variables must be substituted via rewrites first");
            }
            Int::NumLit(n) => *n,
            Int::Add(a, b) => a.eval() + b.eval(),
            Int::Sub(a, b) => a.eval() - b.eval(),
        }
    }
}

/// Parse and evaluate a statement (assignment or expression) with environment.
/// Returns the computed value.
pub fn parse_and_eval_with_env(
    input: &str,
    env: &mut CalculatorEnv,
) -> Result<i32, String> {
    mettail_runtime::clear_var_cache();

    let trimmed = input.trim();

    // Check if it's an assignment
    if let Some(eq_pos) = trimmed.find('=') {
        let var_part = trimmed[..eq_pos].trim();
        let expr_part = trimmed[eq_pos + 1..].trim();

        // Validate variable name (no operators in LHS)
        if !var_part.chars().all(|c| c.is_alphanumeric() || c == '_') {
            return Err(format!("Invalid variable name: {}", var_part));
        }

        // Parse the RHS expression (may contain variables)
        let parser = calculator::IntParser::new();
        let expr = parser
            .parse(expr_part)
            .map_err(|e| format!("parse error: {:?}", e))?;

        // Apply rewrites to substitute variables
        let rewritten = apply_rewrites_with_env(expr, env)?;

        // Check for remaining variables (undefined variables)
        if has_var_ref(&rewritten) {
            return Err("undefined variable in expression".to_string());
        }

        let val = rewritten.eval();
        env.set(var_part.to_string(), val);
        Ok(val)
    } else {
        // Parse the expression (may be a variable reference or expression)
        let parser = calculator::IntParser::new();
        let expr = parser
            .parse(trimmed)
            .map_err(|e| format!("parse error: {:?}", e))?;

        // Apply rewrites to substitute variables
        let rewritten = apply_rewrites_with_env(expr, env)?;

        // Check for remaining variables (undefined variables)
        if has_var_ref(&rewritten) {
            // Try to extract variable name for better error message
            if let Some(var_name) = extract_var_name(&rewritten) {
                return Err(format!("undefined variable: {}", var_name));
            }
            return Err("undefined variable".to_string());
        }

        Ok(rewritten.eval())
    }
}

/// Check if a term contains any VarRef nodes
fn has_var_ref(term: &Int) -> bool {
    match term {
        Int::VarRef(_) => true,
        Int::NumLit(_) => false,
        Int::Add(a, b) => has_var_ref(a) || has_var_ref(b),
        Int::Sub(a, b) => has_var_ref(a) || has_var_ref(b),
    }
}

/// Extract variable name from a VarRef term (for error messages)
fn extract_var_name(term: &Int) -> Option<String> {
    match term {
        Int::VarRef(ord_var) => {
            match ord_var {
                mettail_runtime::OrdVar(mettail_runtime::Var::Free(ref fv)) => {
                    fv.pretty_name.clone()
                }
                _ => None,
            }
        }
        Int::NumLit(_) => None,
        Int::Add(a, b) => extract_var_name(a).or_else(|| extract_var_name(b)),
        Int::Sub(a, b) => extract_var_name(a).or_else(|| extract_var_name(b)),
    }
}

/// Parse an input string (simple integers and + / -) and evaluate it.
/// With native types, integers parse directly without preprocessing.
pub fn parse_and_eval(input: &str) -> Result<i32, String> {
    // Clear var cache so variable identities are fresh for this parse
    mettail_runtime::clear_var_cache();

    // Use the generated parser module (lalrpop will generate `calculator` module)
    // With native types, integers parse directly via the Integer token
    let parser = calculator::IntParser::new();
    // The parser returns our generated `Int` type
    let expr = parser
        .parse(input)
        .map_err(|e| format!("parse error: {:?}", e))?;

    Ok(expr.eval())
}
